language: node_js
node_js:
  - "0.10"
before_install:
  - time sudo pip install --use-mirrors -r test-infra/requirements.txt
  - rvm use 1.9.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)
  - if [ "$TWBS_TEST" = validate-html ]; then echo "ruby=$(basename $GEMDIR) jekyll=$JEKYLL_VERSION" > pseudo_Gemfile.lock; fi
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip sauce\]'; export TWBS_DO_SAUCE=$?; true
install:
  - time npm install -g grunt-cli
  - ./test-infra/s3_cache.py download npm-modules
  - if [ "$TWBS_TEST" = validate-html ] && [ $TWBS_DO_VALIDATOR -ne 0 ]; then ./test-infra/s3_cache.py download rubygems; fi
after_script:
  - if [ "$TWBS_TEST" = core ]; then ./test-infra/s3_cache.py upload npm-modules; fi
  - if [ "$TWBS_TEST" = validate-html ] && [ $TWBS_DO_VALIDATOR -ne 0 ]; then ./test-infra/s3_cache.py upload rubygems; fi
env:
  global:
    - JEKYLL_VERSION: 1.5.0
    - SAUCE_USERNAME: gvas-grunt-saucelabs
    - secure: "jz0VwlVoYQ4+9HkI/7YLcfpbNNSeq9gzfCEVRgCKhDB/XQ3oHJT5ga72b/SE5QrvaxRpqRbW/SZw128rwBUI20iYTQYHHb5oQyrYB/OQlzh5gvjWI/d1GYIX35+oe0RYS8LndXxJySEShmbdPlgNKLK6jaXtTN4zcOIDaKC9L7M="
  matrix:
    - TWBS_TEST=core
    - TWBS_TEST=validate-html
    - TWBS_TEST=sauce-js-unit
matrix:
  fast_finish: true
notifications:
  slack: heybb:iz4wwosL0N0EdaX1gvgkU0NH
